// Generated by https://quicktype.io

export interface SerpResponse {
  search_metadata: SearchMetadata
  search_parameters: SearchParameters
  search_information: SearchInformation
  shopping_results: ShoppingResult[]
  local_map: LocalMap
  local_results: LocalResults
  knowledge_graph: KnowledgeGraph
  inline_images: InlineImage[]
  related_questions: RelatedQuestion[]
  organic_results: OrganicResult[]
  related_searches: RelatedSearch[]
  pagination: Pagination
  serpapi_pagination: Pagination
}

export interface InlineImage {
  link: string
  source: string
  thumbnail: string
}

export interface KnowledgeGraph {
  title: string
  type: string
  header_images: HeaderImage[]
  description: string
  source: KnowledgeGraphSource
  acidity_level: string
  acidity_level_links: AcidityLevelLink[]
  people_also_search_for: PeopleAlsoSearchFor[]
  people_also_search_for_link: string
  people_also_search_for_stick: string
  list: { [key: string]: string[] }
}

export interface AcidityLevelLink {
  text: string
  link: string
}

export interface HeaderImage {
  image: string
  source: string
}

export interface PeopleAlsoSearchFor {
  name: string
  link: string
  serpapi_link: string
  image: string
}

export interface KnowledgeGraphSource {
  name: string
  link: string
}

export interface LocalMap {
  link: string
  image: string
  gps_coordinates: LocalMapGpsCoordinates
}

export interface LocalMapGpsCoordinates {
  latitude: number
  longitude: number
  altitude: number
}

export interface LocalResults {
  more_locations_link: string
  places: Place[]
}

export interface Place {
  position: number
  title: string
  place_id: string
  lsig: string
  place_id_search: string
  reviews: number
  price?: string
  type: string
  hours: string
  address: string
  thumbnail: string
  gps_coordinates: PlaceGpsCoordinates
  description?: string
}

export interface PlaceGpsCoordinates {
  latitude: number
  longitude: number
}

export interface OrganicResult {
  position: number
  title: string
  link: string
  displayed_link: string
  thumbnail?: string
  snippet: string
  snippet_highlighted_words: string[]
  sitelinks?: Sitelinks
  rich_snippet?: RichSnippet
  about_this_result: AboutThisResult
  about_page_link: string
  about_page_serpapi_link: string
  cached_page_link?: string
  related_pages_link?: string
  date?: string
}

export interface AboutThisResult {
  source: AboutThisResultSource
}

export interface AboutThisResultSource {
  description: string
  source_info_link: string
  security: string
  icon?: string
}

export interface RichSnippet {
  bottom: Bottom
}

export interface Bottom {
  extensions: string[]
  detected_extensions: DetectedExtensions
}

export interface DetectedExtensions {
  introduced_th_century: number
}

export interface Sitelinks {
  inline: Inline[]
}

export interface Inline {
  title: string
  link: string
}

export interface Pagination {
  current: number
  next: string
  other_pages: { [key: string]: string }
  next_link?: string
}

export interface RelatedQuestion {
  question: string
  snippet: string
  title: string
  link: string
  displayed_link: string
  next_page_token: string
  serpapi_link: string
  thumbnail?: string
}

export interface RelatedSearch {
  query: string
  link: string
}

export interface SearchInformation {
  organic_results_state: string
  query_displayed: string
  total_results: number
  time_taken_displayed: number
  menu_items: MenuItem[]
}

export interface MenuItem {
  position: number
  title: string
  link?: string
  serpapi_link?: string
}

export interface SearchMetadata {
  id: string
  status: string
  json_endpoint: string
  created_at: string
  processed_at: string
  google_url: string
  raw_html_file: string
  total_time_taken: number
}

export interface SearchParameters {
  engine: string
  q: string
  location_requested: string
  location_used: string
  google_domain: string
  hl: string
  gl: string
  device: string
}

export interface ShoppingResult {
  position: number
  block_position: string
  title: string
  price: string
  extracted_price: number
  link: string
  source: string
  rating?: number
  reviews?: number
  thumbnail: string
  extensions?: string[]
}
